#!/usr/bin/env bash
# Configure Nginx to listen on port 80 of all server's active IPv4 IPs

# Modify the main Nginx configuration file to listen on port 80
sudo sed -i "s/listen 80 default_server;/listen 80;/g" /etc/nginx/nginx.conf

# Restart Nginx service to apply changes
sudo service nginx restart

